### ISSUE TITLE
シーン遷移の機能を実装

### ISSUE THREAD

**Issue by id-isymhrk** [id-isymhrk/UnityThon_Team4#38]
**提案の詳細**
シーンがそれぞれ独立しているので、このシーン間の遷移や情報の共有が行えるようにします。
**動機**

**その他**

**Comment by nohahanon** [comment]
メモ
各シーンにGameManager用の空オブジェクトを置く
シーン遷移のきっかけを見張るif文をupdateの中に置く。
sceneプロパティ

title->game :titleシーンにいるかつボタンクリックで遷移
game->result(game clear)　:アイテムを全て収集した状態でドアの前に辿り着けたら遷移
game->result(game over)　:赤べこと接触で遷移
result->title　:ボタンクリックで遷移
