### ISSUE TITLE
[Feature]行動ごとにSEを流す処理

### ISSUE THREAD

**Issue by id-isymhrk** [id-isymhrk/UnityThon_Team4#60]
**提案の詳細**
アイテムを取ったり、歩行などの行動によって効果音を付与する機能を実装してください
**動機**

**その他**

**Comment by nohahanon** [comment]
メモ
移動している場合(フレーム間でpositionの値が異なる場合)
アイテム取得時

無関係なシーン内でテストする

**Comment by nohahanon** [comment]
スクリプトは完成した
あとはunityでのアタッチとpublicのところに使う音源をセット・音量調整をする
grabItemとplayerControllerについて！
